<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Typesafe.With.Generator\Typesafe.With.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="true"/>
    <ProjectReference Include="..\Typesafe.With\Typesafe.With.csproj" />
  </ItemGroup>
</Project>
