<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Typesafe.With\Typesafe.With.csproj" />
    <PackageReference Include="Mono.Reflection.Core" Version="1.1.1" />
  </ItemGroup>

</Project>
